version: '3'
services:
  dummy:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: ['yarn', 'dev']
    volumes:
      - .:/var/www/
      - /var/www/node_modules
      - ./env/client/.env.local:/var/www/.env
    ports:
      - '3001:3000'
    stdin_open: true
    tty: true
